import Head from 'next/head';
import Image from 'next/image';
import HeroSection from '../componens/HeroSection';
import styles from '../styles/Home.module.css';
import useAxios from "../hooks/useAxios";
import Loading from '../componens/Loading';
import { useEffect } from 'react';
import SliderContainer from '../componens/SlideContainer';


const baseUrl = "https://api.themoviedb.org/3/"
const moviesEndpoint = "movie/now_playing"
const tvEndpoint = "tv/airing_today"
const token = "301b07456b1452abbdda1e23bf72876d"

export default function Home() {

  const [moviesRes, fetchMovie] = useAxios()
  const [tvRes, fetchTv] = useAxios()

  useEffect(() => {
    fetchMovie(baseUrl+moviesEndpoint+"?api_key="+token)
    fetchTv(baseUrl+tvEndpoint+"?api_key="+token)
  }, []);

  const dataSlider = [
    {
      title: "Cinema",
      value: moviesRes?.data?.results
    },
    {
      title: "TV",
      value: tvRes?.data?.results
    }
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>TMDB Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tmdb.png" />
      </Head>

      <main>
        <HeroSection />

        <div>
          {
            moviesRes.loading ?
              <Loading />
              :
              <SliderContainer title={"NEW RELEASE"} data={dataSlider} />
          }
        </div>
        


      </main>

    </div>
  )
}
